### PR TITLE
Created Notes sheets

### PR DESCRIPTION
**Pull request by itsTHL**
Created a sheet with first part of my notes including list of basic commands, options and shortcuts

### CODE REVIEW

**Comment by tonelloalan** [comment]
Looking pretty good and covering many commands 👍

**Review by j-schilling — COMMENTED** [review]
Hi Tina, great job! I copied your notes. Hope this does not count as plagiarism! :flushed:

**Review by TS-Severin — COMMENTED** [review]
Great list, thank you! I will follow Janosch and plagiarize it ;-)

**Comment by itsTHL** [comment]
> Looking pretty good and covering many commands 👍

Thank you!

**Comment by itsTHL** [comment]
> Hi Tina, great job! I copied your notes. Hope this does not count as plagiarism! 😳

Thanks! Feel free, you officially have my permission. :)

**Pull request merged**
